source 'https://supermarket.chef.io'

metadata

group :delivery do
  cookbookName 'delivery_build', git: 'https://github.com/chef-cookbooks/delivery_build'
  cookbookName 'delivery-base', git: 'https://github.com/chef-cookbooks/delivery-base'
  cookbookName 'test', path: './test/fixtures/cookbooks/test'
end
